### ISSUE TITLE
A way to retrieve a list of HEIs for which a particular API has been implemented

### ISSUE THREAD

**Issue by mikesteez** [erasmus-without-paper/ewp-registry-client#1]
How do you list EWP hosts? 

The `ClientImpl` has methods to filter APIs but I can't find a way to only list the available EWP hosts. This is a central use case for the reference connector.

**Comment by wrygiel** [comment]
I haven't seen any use for such method, so there isn't any. Could you explain why do you need it?

**Comment by mikesteez** [comment]
When a new IIA is created, the user will select the partner institution from a list of institutions

**Comment by wrygiel** [comment]
Then you are looking for the list of institutions, not the list of EWP Hosts, I think?

**Comment by mikesteez** [comment]
Yes, correct!

**Comment by wrygiel** [comment]
My first thought was to use the `findApis` method, but this method returns API entries only, without HEI IDs. There's also no method to retrieve names of HEIs, and that would be good to have (otherwise you would need to query Institutions API to get these names). You're right, something is missing here...

**Comment by wrygiel** [comment]
```
Collection<Hei> findHeis(ApiSearchConditions conditions)
```

This would return a list of HEIs for which at least one API has been implemented which matches the given `conditions`. `Hei` would be a simple wrapper for the [`<hei>` element](https://github.com/erasmus-without-paper/ewp-specs-api-registry/blob/v1.0.2/catalogue.xsd#L184).

Is this what what you need?

**Comment by mikesteez** [comment]
If the `ApiSearchConditions` can be without any conditions, this would be great.

**Comment by wrygiel** [comment]
> If the ApiSearchConditions can be without any conditions, this would be great.

It can, but I'd guess that in your particular case you will want to put IIAs API there? Or not?

**Comment by wrygiel** [comment]
IIAs are stored locally, so all kinds of HEIs may participate it them. Even the ones that haven't implemented the IIAs API, or the ones that are not part of the EWP Network. So, I'm just wandering how this will look in your application. But perhaps it's not a good place for this discussion :)

**Comment by wrygiel** [comment]
Version `1.2.0` should be already downloadable from Maven Central.
