### ISSUE TITLE
Test GenericTests.testReadingResources fails on Windows

### ISSUE THREAD

**Issue by BoukeNijhuis** [erasmus-without-paper/ewp-registry-client#12]
The test GenericTests.testReadingResources() assumes that a line ends with \n. This true on most operating systems, but not on Windows. Therefore I adjusted the test to be OS independent. PR incoming.

**Comment by wrygiel** [comment]
I think it depends on how you check out your Git repository. So this change can break for someone how checks it out "as is".

(I'm no longer the maintainer of this, it's just a comment for other reviewers.)

**Comment by BoukeNijhuis** [comment]
You are totally right. I have updated to PR to prevent this problem. In this I assumed the EOL in the test is not relevant for the test.
