### ISSUE TITLE
CatalogueDocument.cliKeyHeis does not seem to be populated correctly

### ISSUE THREAD

**Issue by mpuzar** [erasmus-without-paper/ewp-registry-client#7]
Registry Client cannot find my host, neither with `isClientKeyKnown()` nor `getHeisCoveredByClientKey()`. `Utils.extractFingerprint()` does seem to get this part correctly though: a859625706688a24778da061211f2c3565b4847e5c95a207c195556f89d7a1c6

Any ideas?

**Comment by wrygiel** [comment]
It's because your key `a859625706688a24778da061211f2c3565b4847e5c95a207c195556f89d7a1c6` is declared as server key, not a client key.

**Comment by mpuzar** [comment]
Duh, of course. Thanks.
